name: Get repo name
description: >
  Returns repository name without the owner.


outputs:
  name:
    description: "Repository name"
    value: ${{ steps.repo.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Get repo name
      id: repo
      shell: pwsh
      run: |
        Add-Content -Path $env:GITHUB_OUTPUT -Value "name=$('${{github.repository}}'.Replace('${{github.repository_owner}}/','').ToLower())"
